# helmrelease
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-metrics-k8s-stack
  namespace: victoria-metrics
spec:
  interval: 24h0m
  chart:
    spec:
      chart: victoria-metrics-k8s-stack
      version: 0.71.x
      sourceRef:
        kind: HelmRepository
        name: victoria-metrics
  install:
    createNamespace: false
  
  values:
    vmsingle:
      enabled: true
      spec:
        retentionPeriod: 7d
        storage:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
        resources:
          requests:
            memory: 512Mi
            cpu: 250m
          limits:
            memory: 1Gi
            cpu: 1000m

    vmagent:
      enabled: true
      spec:
        scrapeInterval: 30s

# enabled parts
    kubeDns:
      enabled: true
      service:
        enabled: true

    prometheus-node-exporter:
      enabled: true
      fullnameOverride: "node-exporter"

    kube-state-metrics:
      enabled: true
      fullnameOverride: "kube-state-metrics"

    victoria-metrics-operator:
      fullnameOverride: "victoria-metrics-operator"

# disabled parts
    grafana:
      enabled: false

    coreDns:
      enabled: false
      service:
        enabled: false

    kubeEtcd:
      enabled: false
      service:
        enabled: false

    kubeScheduler:
      enabled: false
      service:
        enabled: false

    kubeControllerManager:
      enabled: false
      service:
        enabled: false